// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
        appId: '1:509431177707:web:00172799528985a20179ae',
        messagingSenderId: '509431177707',
        projectId: 'oh-scanada',
        authDomain: 'oh-scanada.firebaseapp.com',
        storageBucket: 'oh-scanada.firebasestorage.app',
        measurementId: 'G-D3ZLJKMSE7',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
        appId: '1:509431177707:android:71a683ae2f6c76550179ae',
        messagingSenderId: '509431177707',
        projectId: 'oh-scanada',
        storageBucket: 'oh-scanada.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
        appId: '1:509431177707:ios:aa2a01b9b26b14740179ae',
        messagingSenderId: '509431177707',
        projectId: 'oh-scanada',
        storageBucket: 'oh-scanada.firebasestorage.app',
        iosBundleId: 'com.example.ohScanada',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
        appId: '1:509431177707:ios:aa2a01b9b26b14740179ae',
        messagingSenderId: '509431177707',
        projectId: 'oh-scanada',
        storageBucket: 'oh-scanada.firebasestorage.app',
        iosBundleId: 'com.example.ohScanada',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
        appId: '1:509431177707:web:26cf1573679671700179ae',
        messagingSenderId: '509431177707',
        projectId: 'oh-scanada',
        authDomain: 'oh-scanada.firebaseapp.com',
        storageBucket: 'oh-scanada.firebasestorage.app',
        measurementId: 'G-M17B0KB54D',
      );
}